[Main]
	path_gdt = /Users/sommeru/src/sono-importer/gdt
	path_image_in = /Users/sommeru/src/sono-importer/in/image
	path_image_out = /Users/sommeru/src/sono-importer/out
	path_ignore = /Users/sommeru/src/sono-importer/ignore
	file_gdt = patient.gdt
	listOfJunkFiles = $RECYCLE.BIN, .AppleDouble, .com.apple.timemachine.donotpresent, .com.apple.timemachine.supported, .DocumentRevisions-V100, .dropbox.cache, .dropbox, .DS_Store, .fseventsd, .LSOverride, .Spotlight-V100, .TemporaryItems, .Trashes, Desktop.ini, ehthumbs.db, Thumbs.db

[Siemens-Accuson]
	font = arial-bold.ttf
	font_size = 15
	font_color = bbbbbb
	name_x = 400
	name_y = 18
	dob_x = 400
	dob_y = 33
	size_x = 800
	size_y = 600


[Samsung-HS30]
	font = arial.ttf
	font_size = 23
	font_color = adadab
	name_x = 391
	name_y = 26
	dob_x = 666
	dob_y = 52
	size_x = 1232
	size_y = 924

[GE-Logiq-P9]
	font = arial-bold.ttf
	font_size = 22
	font_color = 8b8b8b
	name_x = 662
	name_y = 29
	dob_x = 662
	dob_y = 54
	size_x = 1280
	size_y = 1024

